version: 2.1

jobs:
  deploy:
    parameters:
      distro:
        type: string
      version:
        type: string
    working_directory: /
    docker:
      - image: atotto/mutter:<< parameters.distro >>-<< parameters.version >>
    steps:
      - run:
          name: setup atotto packagecloud
          command: |
            apt update && apt install -y curl
            curl -s https://packagecloud.io/install/repositories/atotto/debian-utils/script.deb.sh | os=any dist=any bash
            apt install -y packagecloud
      - run:
          name: deploy packagecloud
          command: |
            packagecloud push atotto/mutter/<< parameters.distro >>/<< parameters.version >> /build/*.deb

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy:
          distro: ubuntu
          version: jammy
      - deploy:
          distro: ubuntu
          version: focal
      - deploy:
          distro: ubuntu
          version: groovy